create or replace view V_NEXT_TERM_REF as
with SCHOOL_GRADE_TERM_LU as (
select SCHOOL_GRADE_TERM_ID, SCHOOL_ID, IS_BOARDING, GRADE_ID, GRADE_ORDER, GRADE, TERM_BEGIN, TERM_END, TERM, SCHOOL_YEAR, GRADE_RANK, TERM_RANK_IN_YEAR,
       max(TERM_RANK_IN_YEAR) over (partition by SCHOOL_ID, IS_BOARDING) MAX_TERM_RANK_IN_YEAR
from (
select SCHOOL_GRADE_TERM.SCHOOL_GRADE_TERM_ID, 
       SCHOOL_GRADE_REF.SCHOOL_ID, 
       GRADE.IS_BOARDING, 
       GRADE.GRADE_ID, 
       GRADE.GRADE_ORDER, 
       GRADE.NAME GRADE,
       SCHOOL_GRADE_TERM.TERM_BEGIN, 
       SCHOOL_GRADE_TERM.TERM_END, 
       TERM.NAME TERM,
       TERM.SCHOOL_YEAR,
       dense_rank() over (partition by SCHOOL_GRADE_REF.SCHOOL_ID, GRADE.IS_BOARDING order by GRADE.GRADE_ORDER) GRADE_RANK,
       rank() over (partition by SCHOOL_GRADE_REF.SCHOOL_ID, SCHOOL_GRADE_REF.GRADE_ID, GRADE.IS_BOARDING, TERM.SCHOOL_YEAR order by SCHOOL_GRADE_TERM.TERM_END) TERM_RANK_IN_YEAR

from SCHOOL_GRADE_TERM
join SCHOOL_GRADE_REF on SCHOOL_GRADE_TERM.SCHOOL_GRADE_REF_ID=SCHOOL_GRADE_REF.SCHOOL_GRADE_REF_ID
join GRADE on SCHOOL_GRADE_REF.GRADE_ID=GRADE.GRADE_ID
join TERM on SCHOOL_GRADE_TERM.TERM_ID=TERM.TERM_ID)
)
select SGT_LU.SCHOOL_GRADE_TERM_ID, 
       SGT_LU.SCHOOL_ID, 
       SGT_LU.IS_BOARDING, 
       SGT_LU.GRADE_ID, 
       SGT_LU.GRADE,
       SGT_LU.TERM_BEGIN, 
       SGT_LU.TERM_END,  
       SGT_LU.TERM,
       SGT_LU2.SCHOOL_GRADE_TERM_ID NEXT_SCHOOL_GRADE_TERM_ID, 
       SGT_LU2.GRADE_ID NEXT_GRADE_ID, 
       SGT_LU2.GRADE NEXT_GRADE,
       SGT_LU2.TERM_BEGIN NEXT_TERM_BEGIN, 
       SGT_LU2.TERM_END NEXT_TERM_END,
       SGT_LU2.TERM NEXT_TERM
from SCHOOL_GRADE_TERM_LU SGT_LU
left join SCHOOL_GRADE_TERM_LU SGT_LU2 on SGT_LU.SCHOOL_ID=SGT_LU2.SCHOOL_ID and 
                                          SGT_LU.IS_BOARDING=SGT_LU2.IS_BOARDING and
                                          ((SGT_LU.SCHOOL_YEAR=SGT_LU2.SCHOOL_YEAR and SGT_LU.TERM_RANK_IN_YEAR+1=SGT_LU2.TERM_RANK_IN_YEAR and SGT_LU.GRADE_RANK=SGT_LU2.GRADE_RANK) or
                                           (SGT_LU.SCHOOL_YEAR+1=SGT_LU2.SCHOOL_YEAR and SGT_LU2.TERM_RANK_IN_YEAR=1 and SGT_LU.GRADE_RANK+1=SGT_LU2.GRADE_RANK and SGT_LU.TERM_RANK_IN_YEAR=SGT_LU.MAX_TERM_RANK_IN_YEAR))
